name: Deploy to sandpit
on:
  push:
    paths:
      - 'infrastructure/cloudformation/td-cpe-sandpit-role.yaml'

  # pull_request_target:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  #   paths:
  #     - 'infrastructure/cloudformation/td-cpe-sandpit-role.yaml'
permissions:
  id-token: write
  contents: read

jobs:
  update_aws_stack:
    name: update aws stack
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # This defines which enviornment to get variables/secrets from
    environment: sandpit

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "send MS teams notification"
        uses: ./.github/actions/teams-msg
        with:
          webhook-url: ${{vars.MSTEAMS_WEBHOOK}}
          message: "STARTING - Deploy to sandpit"

      - name: "configureawscredentials"
        uses: "aws-actions/configure-aws-credentials@v2"
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN }}
          role-session-name: "LeeGithubSandpitTest"
          aws-region: ${{vars.AWS_DEFAULT_REGION}}