name: Deploy to sandpit
on:
      workflow_dispatch:      
  # pull_request_target:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  #   paths:
  #     - 'infrastructure/cloudformation/td-cpe-sandpit-role.yaml'
permissions:
  id-token: write
  contents: read

jobs:
  update_aws_stack:
    name: update aws stack
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # This defines which enviornment to get variables/secrets from
    environment: sandpit

    steps:
      - name: "configureawscredentials"
        uses: "aws-actions/configure-aws-credentials@v2"
        with:
          role-to-assume: ${{vars.CPE_WORKSHOP_GITHUB_ROLE_SANDPIT1}}
          role-session-name: "sswamina01SandpitGithub"
          aws-region: "ap-southeast-2"

          

      - name: "AWS S3 list buckets"
        run: |
           aws --region ap-southeast-2 s3 ls

              - name: "AWS S3 list buckets"
        run: |
           echo "updating file in s3" > HappyThursday.txt
           aws s3 cp HappyThursday.txt s3://automation-workshop-ash/object.txt
